### ISSUE TITLE
On entry to Reviews page, need to launch "review output()"

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#123]

**Comment by gnkatchmar** [comment]
Waiting for Navigation to be complete to add listener to Reviews link

**Comment by djado** [comment]
I tried to call this func but it seems to be buried inside another function.
Once this is fixed, you can uncomment line 41 in changePages.js to call it without error.
While you're in there, can you remove the 'Advanced Search' button in index.html?
