### ISSUE TITLE
Everyone-delete your older branches off of GitHub

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#127]

**Comment by gnkatchmar** [comment]
Takes only a minute. Click Branches, and should see a list of your branches, followed by a list of everyone's branches.

**Comment by djado** [comment]
Done!

**Comment by jjj430** [comment]
done

**Comment by ccruz07** [comment]
done except for last file I just uploaded, Google Fonts

**Comment by gnkatchmar** [comment]
Cleaned out the last of the older strays-some, including my own, may not have deleted properly in the first goaround.
