### ISSUE TITLE
Thumbs wingding not appearing in my browser (see img)

### ISSUE THREAD

**Issue by djado** [gnkatchmar/Breakfast-Club#136]
![thumbs](https://cloud.githubusercontent.com/assets/9664086/17790117/fb159360-6549-11e6-98f6-a16069887d3f.png)

**Comment by gnkatchmar** [comment]
My result:
![image](https://cloud.githubusercontent.com/assets/20120982/17790592/011cd21c-654c-11e6-8edc-804326c8ee75.png)

**Comment by djado** [comment]
I think this is due to you having a font installed that I do not (I tried both Firefox and Chrome).
While I like the character, I don't think we can count on user's having certain fonts.
An image is preferable I think.
