### ISSUE TITLE
Everyone should read Getting Started with the Google Maps API

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#14]
It will be a key component of the project: https://developers.google.com/maps/documentation/javascript/tutorial

[Thanks, Jade]

**Comment by ccruz07** [comment]
read the map article, are we ready to start developing this part of app yet?

**Comment by jjj430** [comment]
Here is link with a little easier read:

http://www.w3schools.com/googleapi/
