### ISSUE TITLE
Spielman title is too long for display (see img)

### ISSUE THREAD

**Issue by djado** [gnkatchmar/Breakfast-Club#145]
![spielman](https://cloud.githubusercontent.com/assets/9664086/17792469/b8567e2a-6555-11e6-9aea-f21e92604199.png)

**Comment by gnkatchmar** [comment]
Change to just (SE) and (NE)?

**Comment by djado** [comment]
Their website says 'Spielman Bagels'
So add a (SE) an (NE) to the end?
Works for me!
