### ISSUE TITLE
Function-text version of advanced search results (list or table with hyperlink capability)

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#15]
After map generates for advanced search, have a button beneath giving user option to generate a straightforward list of restaurants, addresses, and opening hours. Probably adjacent to a "search again" and "quit' buttons. OR have list automatically generate after map so no need for a button.

**Comment by jjj430** [comment]
I was wondering if we should have another page?  There seem to be a lot of stuff on one page.

**Comment by gnkatchmar** [comment]
Should be able to repurpose Cookie Stand: Heading would be time (in half-hour increments), and rows would be: restaurant name/url and address.
