### ISSUE TITLE
Why are Search checkboxes being reset to all unchecked?

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#160]
In HTML they are set as all checked. Moreover, the local storage of the three checkboxes is being overwritten. Yet, the local storage of the time dropdown still works.

If there is a valid reason for this, the local storage aspect of this can be removed (and the HTML tidied up as to the "checked" designations, including the erroneous designation in time dropdown) because the local storage requirement for project guidelines is being met by the Review page.

I think removal of this would help in getting the user to trigger the table.

**Comment by djado** [comment]
Sorry. Was trying to isolate why starting map position was off last night and wanted to take the checkboxes out of the equation. This does not seem to have been the issue though.

Feel free to comment this out (line 163 in geolocation.js) or I will include it later in my next PR.
