### ISSUE TITLE
Only one review is showing even though I submitted 2

### ISSUE THREAD

**Issue by djado** [gnkatchmar/Breakfast-Club#175]
The thumbs up/down for both reviews show inline on top of first review.

**Comment by gnkatchmar** [comment]
Working as intended. One line for each restaurant, each separate review enclosed in quotes, separated by a space. See attached. 
![image](https://cloud.githubusercontent.com/assets/20120982/17827663/b9008b32-6635-11e6-86af-5fd6c51ccc75.png)

**Comment by gnkatchmar** [comment]
Could just as easily separate each review on it's own line if preferred.

**Comment by djado** [comment]
That would be ideal. Otherwise it would be hard to tell where one review ends and another begins.
