### ISSUE TITLE
Consider second input screen-what to ask?

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#24]
"Review the Ap" would technically be sufficient, but let's brainstorm on something relevant to the brunch experience

**Comment by djado** [comment]
Maybe we could let users add their own brunch spots?

**Comment by jjj430** [comment]
That would be cool to add their own.  Would the new place be added to our map?

**Comment by gnkatchmar** [comment]
Unsure if user would also be expected to add url, lat & long. If not, how would we programmatically fill in that needed information?

Leaning towards more a comprehensive user feedback screen:  rate the app (use LS to display past rankings maybe with Canvas?), an "add restaurant" input, and general comments.

**Comment by gnkatchmar** [comment]
Maybe a dropdown of the restaurants allowing the user to choose places they've been to and recommend. Store locally and display choices in order of "upvotes." Dropdown can be built using Google Sheet just like the object was built, i.e. no typing necessary.

**Comment by djado** [comment]
The group decided that this will be a rating page including:
- Thumbs-Up/Thumbs-Down style rating
- Textbox allowing a written review
