### ISSUE TITLE
Function-opening map based on proximity to user's geolocation

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#30]
Closest 10 or so?

**Comment by djado** [comment]
I've got the map opening to where the browser _approximates_ the user to be. The catch here is that it can be a pretty rough approximation.

I suggest we modify the spec to open the browser only in the closest quadrant to the user's approximate location.

**Comment by gnkatchmar** [comment]
Tried this from home. Was identified 1.5 blocks NW of true location. Pretty close.
