### ISSUE TITLE
Add featured content & functionality to page 1

### ISSUE THREAD

**Issue by djado** [gnkatchmar/Breakfast-Club#35]
On this page we need 3 images put side by side. Underneath each image is the name of a local brunch restaraunt, and a link to its website. All details for the objects can be found in 'brunchArr'. Photo(s) can be pulled from the Google Places API or from the project's FoodPics folder. For info on our Google Places integration, see [here](https://github.com/gnkatchmar/Breakfast-Club/wiki/Google-Places-Integration).

Under that there is an 'advanced search' button that when pressed hides page 1 (id='launchpage' in index.html), and unhides page 2 (id='searchpage' in index.html).

We haven't decided on a transition here so feel free to come up with something you like :)

These 'featured' restaraunts will be selected in one of two ways, depending on whether the user opts in to geolocation:
- Random selection from brunchArr in app.js (if the user is not using geolocation) -- just like the Bus Mall assignment we did in class.
- Drawn from a subset of close-by brunch spots (if the user opts into geolocation). To get their (very approximate) quadrant (NSEW) use the function: getQuadrant(pos);

**Comment by ccruz07** [comment]
Added three photos from FoodPic folder with restaurant name and website as placeholders.
Added transitions for advance search from pg 1 to pg 2.
Google Places API for photos not used for this task at this time.  TBA

Create a new issue for remainder of this task:
Featured Restaurant
user opts in/out for geolocation

**Comment by ccruz07** [comment]
Reopening this task  for Google Place API photos to be added to pg 1

**Comment by ccruz07** [comment]
Tried to start working with googlePlace js, to add a restaurant photo,  it's causing problems in my text editor, getting duplicate cursors on the  screen, cannot move through it w/o deleting something. Problem started when I pasted the pId from brunchtrack arr into getPhotoPlaces function.

Will troubleshoot later in class.

**Comment by djado** [comment]
Atom editor can use multiple cursors at once.
To create a duplicate cursor you press CTRL while clicking in your editor.
You should be able to switch back to single cursor by just clicking elsewhere in the editor.

**Comment by ccruz07** [comment]
Thanks have tried that,have even closed Atom and reopened, but still problem persists.

**Comment by ccruz07** [comment]
group opting to not use GogglePhotos API for pg 1, will continue to use photos from FoodPics folder
