### ISSUE TITLE
Choose font, color scheme and begin CSS 

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#5]

**Comment by NathanPickard** [comment]
_Style guide for Breakfast-Club_ - (Initial layout)

##Color Scheme##
Body background: lightyellow
Headers:
Image titles:
Page:
Buttons:
Menus:
Checkboxes:
Restaurant Links:

##Fonts##
Page title: Raleway
Image titles:
Headers:
Restaurant links:
Buttons:
Menu header:
Checkboxes:
Links:

##Links to CSS##
 -Google fonts:
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
 -Color scheme picker

**Comment by NathanPickard** [comment]
/*Initial styling from mockups */

h1  {
  font-family: 'Raleway', sans-serif;

}

body  {
  background-color: lightyellow;
}

section {
  font-family: 'Raleway' , sans-serif;
}

**Comment by NathanPickard** [comment]
Layout, colors, and fonts will be added and adjusted according to HTML structure
