### ISSUE TITLE
Launchpage blocks form elements on searchpage

### ISSUE THREAD

**Issue by djado** [gnkatchmar/Breakfast-Club#74]
The launchpage (even though invisible) is blocking access to the form elements. You can see this by setting #launchpage to display:none

**Comment by ccruz07** [comment]
????? not clear what that means,

**Comment by djado** [comment]
When you press the 'Advanced Search' button the launchpage transitions to hidden.
Even though it is invisible, it is still there blocking user access to form checkboxes etc.
