### ISSUE TITLE
Add framing containers and 'visit website' links to featured images

### ISSUE THREAD

**Issue by djado** [gnkatchmar/Breakfast-Club#76]
These should act as frame for photo and content below photo.
Also, change the venue name so it's not a link.
Add 'visit website' text under venue name that links to their website.
Add 'review' text under venue name that links to page3.

**Comment by NathanPickard** [comment]
Just for clarification, there is only going to be one HTML file (index.html) in the entire project, correct?

**Comment by djado** [comment]
That is correct.
