### ISSUE TITLE
search form default/local storage being overwritten by other code

### ISSUE THREAD

**Issue by gnkatchmar** [gnkatchmar/Breakfast-Club#80]
Something is always setting the choice to "SE Portland" only. Setting a breakpoint on my code proves my local storage works...for a nanosecond.

**Comment by djado** [comment]
This is probably line 77 in geolocation.js
If you opt in to geolocation, I set the checkbox for your current location

**Comment by gnkatchmar** [comment]
Ah! Not a bug, it's a feature!
